services:
  projectapi:
    image: ${DOCKER_REGISTRY-}projectapi
    build:
      context: .
      dockerfile: ProjectApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProjectDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - Serilog__WriteTo__0__Name=Seq
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    depends_on:
      - sqlserver
      - seq
    ports:
      - "5000:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      Seq_FIRSTRUN_ADMINUSERNAME: "admin"
      SEQ_FIRSTRUN_ADMINPASSWORD: "StrongPassword123!"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

  sonar_db:
    image: postgres:15-alpine
    container_name: sonar_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    ports:
      - "5432:5432"
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  sqlserver_data:
  jenkins_home:
  seq_data:
  sonar_db_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:

